# Generated by Django 5.1.4 on 2025-01-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_task_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.CharField(blank=True, choices=[('!', 'Low Priority'), ('!!', 'Medium Priority'), ('!!!', 'High Priority'), ('', 'No Priority')], default='', max_length=3),
        ),
    ]
